# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_screen_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_screen(object):
    def setupUi(self, login_screen):
        login_screen.setObjectName("login_screen")
        login_screen.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(login_screen)
        self.centralwidget.setObjectName("centralwidget")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(390, 320, 151, 51))
        self.login_btn.setObjectName("login_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 771, 71))
        self.label.setStyleSheet("font: 75 40pt \"Century Gothic\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(400, 179, 141, 31))
        self.username.setObjectName("username")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 180, 151, 41))
        self.label_2.setStyleSheet("font: 16pt \"Century Gothic\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 240, 151, 41))
        self.label_3.setStyleSheet("font: 16pt \"Century Gothic\";")
        self.label_3.setObjectName("label_3")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(400, 240, 141, 31))
        self.password.setObjectName("password")
        self.error = QtWidgets.QLabel(self.centralwidget)
        self.error.setGeometry(QtCore.QRect(240, 290, 301, 20))
        self.error.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(255, 0, 0);")
        self.error.setText("")
        self.error.setAlignment(QtCore.Qt.AlignCenter)
        self.error.setObjectName("error")
        login_screen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(login_screen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        login_screen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(login_screen)
        self.statusbar.setObjectName("statusbar")
        login_screen.setStatusBar(self.statusbar)

        self.retranslateUi(login_screen)
        QtCore.QMetaObject.connectSlotsByName(login_screen)

    def retranslateUi(self, login_screen):
        _translate = QtCore.QCoreApplication.translate
        login_screen.setWindowTitle(_translate("login_screen", "Login"))
        self.login_btn.setText(_translate("login_screen", "Login"))
        self.label.setToolTip(_translate("login_screen", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("login_screen", "Login"))
        self.label_2.setText(_translate("login_screen", "Username"))
        self.label_3.setText(_translate("login_screen", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_screen = QtWidgets.QMainWindow()
    ui = Ui_login_screen()
    ui.setupUi(login_screen)
    login_screen.show()
    sys.exit(app.exec_())
